### PR TITLE
Resolution timer Performance.now

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
I think wrappers for `clock_time_get` and `clock_res_get` could be improved:
- both could return `u64` instead `f64` (which JS legacy and only one way represent numbers)
- `memory.alloc` could be global and reused instead allocate and free every call for both methods

WDYT?

**Comment by jedisct1** [comment]
Totally agree :)

Merged, thanks!

**Comment by jedisct1** [comment]
Regarding `memory.alloc`, there is still the thread safety issue.

I wish we had to way to allocate objects on the stack. That would be completely unsafe if these ever get returned, but that would also makes a lot of things way faster by avoid unnecessary allocations.

**Comment by MaxGraey** [comment]
Actually currently `memory.allocate` and `memory.free` is not thread safe as well but if you care about future, yeah shared global pointer hasn't thread safety. btw is lucet support atomics for WebAssembly?

**Comment by MaxGraey** [comment]
WebAssembly hasn't shadow stack and can't allocate objects in it unfortunately

**Comment by jedisct1** [comment]
Lucet doesn't support atomics nor threads yet. But we committed to completely support the wasm specification, so these will be implemented.

**Comment by MaxGraey** [comment]
Nice!

**Pull request merged**
