### PR TITLE
Added a package name and version

### PR DESCRIPTION
**Pull request by torch2424**
Hello @jedisct1 !

I made this PR to add a package name and version to the project. Which then, will allow npm to install wasa as a [project dependency from github](https://docs.npmjs.com/cli/install). Which would help me (and hopefully others) out a lot who are already using WASA.

My apologies for not opening an issue first, The PR is so small I figured we could discuss it here if anything 😄

### CODE REVIEW

**Comment by jedisct1** [comment]
Unfortunately, there is already a package named wasa: https://www.npmjs.com/package/wasa

So we either need to rename it, or namespace it 😔

**Comment by MaxGraey** [comment]
Also possible free names:
w-as-i
wasmabi
as-wasi

**Comment by torch2424** [comment]
> So we either need to rename it, or namespace it 😔

Ahhh no worries 👍 Thankfully @MaxGraey gave us some suggestions! 😄 

I'd like to throw in my vote for as-wasi 😄

**Comment by jedisct1** [comment]
Let's go for `as-wasi` then :)

**Comment by torch2424** [comment]
@jedisct1 Awesome! Changed to as-wasi 😄

**Comment by jedisct1** [comment]
Maybe the repo should be moved as well.

**Comment by torch2424** [comment]
> Maybe the repo should be moved as well.

Thanks for moving it 😄

**Pull request merged**
